### ISSUE TITLE
COP NECB defaults not being applied

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#157] opened 2017-01-18 18:14 UTC
NECB reference COP is based upon cooling load that the system requires.   For PSZ and MUA units COPs should be selected based on NECB 2011 Table 5.2.12.1   I assume that PSX and MUA are using Air cooled Unitary Air Conditioners and Heat Pumps.   The .osm generated COPs do not match NECB 2011 for different cooling capacities.

**Comment by phylroy** [comment] 2017-01-31 18:03
Mike now realizes that this is not a bug closing.

**Closed by phylroy** 2017-01-31 18:03 UTC
Labels: severity - Blocker, Standard - NECB-2011
