### ISSUE TITLE
Create Typical mismatch on Supermarket Prototypes

### ISSUE THREAD

**Issue by powskier** [NREL/openstudio-standards#825] opened 2020-06-02 14:39 UTC
Link to issue under measures:
https://github.com/NREL/OpenStudio-measures/issues/327#issue-627370205

Good Morning colleagues,

I have found that the Supermarket template misaligns DEER model and ASHRAE template case names, erroring out.

ASHRAE 90.1-2010 template still has the standards look up looking for DEER case name "

[11:37:23.867682 ERROR] [openstudio.model.Model] Could not find refrigerated case properties for: {"template"=>"90.1-2010", "case_type"=>"Meat Cases Low", "size_category"=>">50k ft2"}.

**Comment by mdahlhausen** [comment] 2020-07-31 22:26
@carlobianchi89 this appears to be missing information in the the openstudio-standards 90.1 spreadsheet.
'Meat Cases Med' is listed but not 'Meat Cases Low'.

**Comment by carlobianchi89** [comment] 2020-08-10 16:07
@powskier I think I might have fixed the issue, but I am trying to reproduce the error to make sure. 
Could you post the model that failed? I tried to apply create_typical_building_from_model on a DEER grocery store model, but it failed for different reasons.

**Comment by carlobianchi89** [comment] 2020-08-11 20:00
@mdahlhausen I fixed the missing cases. When I tried to test the model_add_typical_refrigeration method, the following error popped up:
"[...] cannot set Schedule Refrigerated Case Restocking=Always Off Discrete because it has an incompatible ScheduleTypeLimits"

Cases that are supposed to have RestockingSchedules set to "always off" have been modified. Instead of setting the restocking schedule to "alwaysOffDiscreteSchedule", the method resetRefrigeratedCaseRestockingSchedule() has been used. 
Everything has been committed and pushed on the "new-90-1-standards" branch.

**Comment by mdahlhausen** [comment] 2020-08-11 21:28
@carlobianchi89 please revert [this commit](https://github.com/NREL/openstudio-standards/commit/eaba4b60c855b1626830509e8d51e642cd53e80d) on that branch and make a new branch off of master with just the changes for the refrigeration fix.

In general for bug fixes, make a branch dedicated to that bug, and separate out commits so that all commits are related to the same change.  In this case, the fix was added to a feature branch that won't be added into openstudio-standards for some time and was bundled with several other changes to the data export in the same commit.

**Comment by carlobianchi89** [comment] 2020-08-12 13:06
Done

**Comment by powskier** [comment] 2020-08-12 13:23
@mdahlhausen @carlobianchi89 Thank you so much for addressing my bug.  Look forward to taking the standards refrigeration stuff much further!

**Comment by powskier** [comment] 2020-08-12 13:30
> @mdahlhausen @carlobianchi89 Thank you so much for addressing my bug. Look forward to taking the standards refrigeration stuff much further!

@carlobianchi89 my use cases is actually for the 90.1 templates..... and the error I'd gotten I chased through the standards spread sheet and saw that it was a DEER case name being looked up by a 90.1 path and it got confused.  I don't readily have the specific model I'd encountered it on.  But the measure chain was create_bar > create_typ with a SuperMarket building type for a 90.1 vintage.  Hope this is informative.  Thanks for the help.

**Comment by mdahlhausen** [comment] 2020-08-12 23:19
Fixed with #880 and #881

**Closed by mdahlhausen** 2020-08-12 23:19 UTC
Labels: severity - Minor Bug

**Comment by powskier** [comment] 2020-08-18 15:22
@mdahlhausen @carlobianchi89 How do I pull this fix? Do I just repull CreateTypical measure, or the standards?

**Comment by mdahlhausen** [comment] 2020-08-18 15:33
@powskier I made an [interim release of openstudio-standards](https://rubygems.org/gems/openstudio-standards/versions/0.2.12.rc1).  You should be able to `gem install` or `gem update` to get the latest version.  Or, you can install directly from the main branch by following the [developer information](https://github.com/NREL/openstudio-standards/blob/master/docs/DeveloperInformation.md).

**Comment by powskier** [comment] 2020-08-18 16:05
Hi Matt,

Thanks, does it matter what version of OS I am using?  And do I do the gem update at the root directory for OpenStudio?  Eg. C:\openstudio-2.9.1

Regards,
Josh

**Comment by powskier** [comment] 2020-08-18 16:39
Hi Matt,

I get what seems to be a security error when I run:  gem update on the Ruby root

C:\Ruby25-x64>gem update
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

I am just trying to update the new standards gem

Thank you,
Josh

**Comment by mdahlhausen** [comment] 2020-08-18 17:32
@powskier Follow the directions for the [SSL Certificate Update](https://guides.rubygems.org/ssl-certificate-update/).
