### ISSUE TITLE
Sizing for Boiler set to zero for Some climate files. 

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#158] opened 2017-01-18 18:44 UTC
[in.osm.txt](https://github.com/NREL/openstudio-standards/files/714713/in.osm.txt)
Archetype FullServiceRestaurant
Weather File:  CAN_PQ_Kuujjuarapik.719050_CWEC.epw

Fails with the following 
[eplusout.err.txt](https://github.com/NREL/openstudio-standards/files/714716/eplusout.err.txt)

It seems the boiler sizing is setting the capacity to zero.  Have not deteremine if other building types are effected.

Reported at git version commit  c7faa8efe77f3f40153cf1fd10ffa492d5bc1d2b

Note this does work with other weather files.. could be a sizing / design day issue.

**Comment by jblake59** [comment] 2017-01-30 03:17
Problem caused by settings in BTAP::Environment::WeatherData1 data hash created in Weather.Model.rb lines 196-276 for all climate locations that have boiler_fueltype set to 'Electricity' (all Quebec and some other locations). The problem is that the heating coils are set to electric as well as the baseboard_type so there is no hot water use for the primary boiler to be sized to handle! The solution is to either change the air handler heating coils and/or baseboards to 'Hot Water' (mau_heating_coil_type and/or baseboard_type)  and keep the boiler OR keep coils and baseboards as electric and remove the boiler.

**Comment by jblake59** [comment] 2017-01-30 21:50
This issue appears to be linked to #154

**Comment by jblake59** [comment] 2017-01-31 16:40
In discussions with Phylroy decided to change the baseboard_type to 'Hot Water' for all 31 climate cases that have this problem (all cases with boiler_fueltype set to "Electricity'. These were PQ locations in addition to a few in MB, PE and NF.

Note that I've also pasted the WeatherData1 array of hashes into a spreadsheet called "FutureUse_Weather-System_Data.xlsx" and committed this to the btap folder.

**Closed** 2017-01-31 18:03 UTC
Labels: Standard - NECB-2011
