### ISSUE TITLE
Unify naming conventions

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#40] opened 2016-02-11 10:30 UTC
When looking through the code (which is rather big and hard to wrap your head around), it's often confusing to see different naming conventions for the same thing. example:

* building_vintage
* standard
* template

all refer to the same thing (eg '90.1-2007')

Maybe unifying the convention would be a good idea.

**Comment by asparke2** [comment] 2016-02-17 18:38
Agree.  I think I want to go with "Template" because that is what is in the OpenStudio-Standards spreadsheet and also because not all of the options are actually Standards.

**Comment by asparke2** [comment] 2016-02-17 18:39
Duplicate of #30

**Closed by asparke2** 2016-02-17 18:39 UTC
